// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmMDtZPMBxgdbuY8Ms_GqbIkTZBj5S_o4',
    appId: '1:259659337766:web:800e6a7d74929a57b2d6e7',
    messagingSenderId: '259659337766',
    projectId: 'test-1b7eb',
    authDomain: 'test-1b7eb.firebaseapp.com',
    storageBucket: 'test-1b7eb.appspot.com',
    measurementId: 'G-E3QE553EXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs09VGI4eGcvttdbB-93im1xQObVdZHLY',
    appId: '1:259659337766:android:c8a86bde2f1acf7bb2d6e7',
    messagingSenderId: '259659337766',
    projectId: 'test-1b7eb',
    storageBucket: 'test-1b7eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIYE2u_MUmTNledSoQHpqumVnotnyrtvA',
    appId: '1:259659337766:ios:71fc4004411c5275b2d6e7',
    messagingSenderId: '259659337766',
    projectId: 'test-1b7eb',
    storageBucket: 'test-1b7eb.appspot.com',
    iosBundleId: 'com.example.carsShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIYE2u_MUmTNledSoQHpqumVnotnyrtvA',
    appId: '1:259659337766:ios:760f9cd0c9f9bba4b2d6e7',
    messagingSenderId: '259659337766',
    projectId: 'test-1b7eb',
    storageBucket: 'test-1b7eb.appspot.com',
    iosBundleId: 'com.example.carsShop.RunnerTests',
  );
}
