// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA5TCRUH45cua-Ltmb0mfsZ1MAO8gynqA',
    appId: '1:499292308319:web:ecf0249d50d50600c6acea',
    messagingSenderId: '499292308319',
    projectId: 'auto-keep-33d92',
    authDomain: 'auto-keep-33d92.firebaseapp.com',
    databaseURL: 'https://auto-keep-33d92.firebasedatabase.app',
    storageBucket: 'auto-keep-33d92.appspot.com',
    measurementId: 'G-JFQRNHFQ7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMuZ2d8zqeUj8rV49vHbiEtB366py3bZ4',
    appId: '1:499292308319:android:9d785e007fae8765c6acea',
    messagingSenderId: '499292308319',
    projectId: 'auto-keep-33d92',
    storageBucket: 'auto-keep-33d92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp-UZU9ZX8apfqfb3qKikUnDW2BybkIzs',
    appId: '1:499292308319:ios:4a10cad1b511bbe4c6acea',
    messagingSenderId: '499292308319',
    projectId: 'auto-keep-33d92',
    storageBucket: 'auto-keep-33d92.appspot.com',
    iosBundleId: 'com.example.autoKeep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp-UZU9ZX8apfqfb3qKikUnDW2BybkIzs',
    appId: '1:499292308319:ios:c3b092035d4d2ce3c6acea',
    messagingSenderId: '499292308319',
    projectId: 'auto-keep-33d92',
    storageBucket: 'auto-keep-33d92.appspot.com',
    iosBundleId: 'com.example.autoKeep.RunnerTests',
  );
}
